### ISSUE TITLE
Some text missing in MI Music player

### ISSUE THREAD

**Issue by nauthna** [Belmont-Gabriel/MA-XML-MIUI7-Vietnamese#2]
In the new music player interface the text overlaps with other elements and some variables do not have assigned text (page_local_setting, nav_local_song, nav_local_favorite). (I found screenshot on web, same error with vietnamese language)

![195040w44iaaaaanj1o3uf](https://cloud.githubusercontent.com/assets/14971219/10272896/52257f38-6b51-11e5-9349-7b9d84e97066.png)

**Comment by Belmont-Gabriel** [comment]
I've fixed already!
