### ISSUE TITLE
Xiaomi Mi4W report

### ISSUE THREAD

**Issue by divogame** [Belmont-Gabriel/MA-XML-MIUI7-Vietnamese#5]
Lỗi thứ nhất cần fix: đó là loa bị rè, không đươc to và trong như bản adroind 4.4
lỗi thứ 2: quản lý pin tốt hơn nữa là tuyệt vời
lỗi thứ 3: chế độ sạc nhanh quick charge cũng gặp vấn đề, cần chỉnh kernel lại là rất tốt

**Comment by tuan1982** [comment]
cái này ông báo lên trang en.miui.com ở đây đâu có liên quan đến mấy lỗi đó đâu
